routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/admin', function () {
    return view('admin/dashboard');
})->name('admin');

Route::resource('products', ProductController::class);

Route::group(['as'=>'admin.','prefix'=>'/admin','middleware' => ['auth:sanctum', 'verified']], function () {
    
    Route::resource('customer', CustomerController::class);
    Route::get('payment', function () { return view('payment');  });
    
    
    Route::resource('sale', SalesController::class);
    Route::resource('purchase', PurchaseController::class);
    Route::get('managePurchase', function () { return view('admin/purchase.managePurchase');  });
    Route::get('purchaseMaterial', function () { return view('admin/purchase.purchaseMaterial');  });

    // Route::get('/purchase/managePurchase', function () { return view('admin/purchase.managePurchase');  });

    Route::resource('tax', TaxController::class);
    Route::resource('challan', ChallanController::class);
    Route::resource('agreement', AgreementController::class);
    Route::resource('addVehicle', AddVehicleController::class);
    Route::resource('addPolicy', AddPolicyController::class);

   Route::get('profile','AdminController@profile')->name('profile');
   Route::resource('admin',AdminController::class);
   Route::POST('ajaxView', 'PurchaseController@ajaxView');



//    Route::get('updateProfile','AdminController@update')->name('update');




   
    // Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
    
// Route::any('customer/payment', 'CustomerController@payment')->name('payment');
});

app/Models/Purchase.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    use HasFactory;
    protected $fillable = ['mobile', 'name','city','state','address'];
}

app/Http/Controllers/PurchaseController.php
<?php

namespace App\Http\Controllers;
use App\Models\Purchase;
use Illuminate\Http\Request;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $purchase = Purchase::all();

        return view ('admin/purchase.index',compact('purchase'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view ('admin/purchase.create');
        // return Response ::json (array()); 
    }
    public function transaction()
    {
        //
        return view ('admin/purchase.transaction');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $data= $request->validate([
            'mobile' => 'required',  
            'name' => 'required',
            'city' => 'required',
            'address' => 'required',
            'state' => '',
        ]);   
        // $purchase = Purchase::create($data);
        // return Purchase::json($purchase);
        


        Purchase::create($request->all());
     
        return redirect()->route('admin.purchase.index')
                        ->with('success','Suplier Details Added successfully.');
    
                    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return view ('admin/purchase.transaction');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $req)
    {
        $data = Data::find($req->id);
        // $data->name = $req->name;
        // $data->save();

        // return response()->json($data);
        return view('data.edit', compact('userData','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $name = $request->input('name');
        $address = $request->input('address');
        $editid = $request->input('editid');
    
        if($name !='' && $address != ''){
          $data = array('name'=>$name,"address"=>$address);
    
          // Call updateData() method of Page Model
          Page::updateData($editid, $data);
          echo 'Update successfully.';
        }else{
          echo 'Fill all fields.';
        }
    
        exit; 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)



{

}
    
    // {
    //     $item = Purchase::findorFail($id);
    //         if($item->delete())
    //         {
    //         return redirect('admin/purchase/index'. $this->purchase)->with('success', trans('app.' . $this->purchase . '.destroy_success'));
    //     }
    //     return redirect('admin/purchase/index'. $this->purchase)->with('error', trans('app.' . $this->purchase . '.destroy_fail'));
    // }







    // {
    //     return redirect()->route('admin.purchase.index')
    //     ->with('success','Suplier deleted successfully');
    // }
    public function managePurchase()
    {
        return view ('admin/purchase.managePurchase');
    }
    public function purchaseMaterial()
    {
        return view ('admin/purchase.purchaseMaterial');
    }
    public function ajaxView(Request $request)
    {
        // $data = $request();
        

        $data = $request->all();

        // return response()
        // ->json($data);
        return Request::ajax() ? 
        response()->json($purchase,Response::HTTP_OK) 
        : abort(404);
    }

}

resources/views/admin/purchase/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="section__content section__content--p30 mb-5">
  <div id="h">
  </div>
  <div class="container mmt mb-5">
    <div class="row">
      <div class="col-lg-12">
        <div class="card update-form">
          <div class="card-header">
            <h3 class="text-center title-2 font-weight-bold">Add Supplier</h3>
          </div>
          <div class="card-body">
            <form action="{{ route('admin.purchase.store') }}" method="POST">
                  @csrf
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputName">Mobile Number</label>
                  <input type="number" class="form-control" id="inputName" placeholder="Enter Mobile" name="mobile" required="true">
                </div>
                <div class="form-group col-md-6">
                  <label for="inputAmount">Name</label>
                  <input type="text" class="form-control" id="inputAmount" placeholder="Enter Full Name" name="name" required="true">
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputName">City</label>
                  <input type="text" class="form-control" id="inputName" placeholder="Enter City" name="city" required="true">
                </div>
                <div class="form-group col-md-6">
                  <label for="inputPolicyNo">State</label>
                  <input type="text" class="form-control" id="inputPolicyNo" placeholder="" value="Uttarakhand" name="state" required="true" disabled="">
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-12">
                  <label for="inputPolicyNo">Address</label>
                  <input type="text" class="form-control" id="inputPolicyNo" placeholder="Enter Address" name="address" required="true">
                </div>
              </div>
              <button type="submit" class="btn btn1" name="submit">Save</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/purchase/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container mmt mb-5">
<!-- DATA TABLE -->
<div class="card shadow mb-4 datatable-card">
  <div class="card-header py-3">
           <h3 class="mb-4 font-weight-bold ml-sm-1">Manage Suppliers</h3>
           @if ($message = Session::get('success'))
               <div class="alert alert-success">
                     <span>{{ $message }}</span>
               </div>
            @endif
        </div>
  <div class="card-body">
    <div class="table-responsive">
      <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
      
                
        <div class="row">
          <div class="col-sm-12">
            <table class="table table-bordered dataTable no-footer userdatatables" >
              <thead class="btn1">
                <tr role="row">
                  <th>Sl No.</th>
                  <th>Mobile</th>
                  <th>Customer Name</th>
                  <th>City</th>
                  <th>Address</th>
                  <th width="200px">Action</th>
                </tr>
              </thead>
              <tbody id="table-body">
                             <!-- SEARCH CUSTOMER TABLE-->
                             <!-- ALL CUSTOMERS TABLE-->
                             @foreach ($purchase as $guest)
                             <tr>
                                <td>{{ $guest->id }}</td>
                                <td>{{ $guest->mobile }}</td>
                                <td>{{ $guest->name }}</td>
                                <td>{{ $guest->city }}</td>
                                <td>{{ $guest->address }}</td>
                             <td>
                                 <form action="{{ route('admin.purchase.destroy',$guest->id) }}" method="POST"> 
                    
                                     <a class="btn btn-info" href="{{ route('admin.purchase.show',$guest->id) }}">Show</a>
                     
                                     <button class="btn btn-primary editModalBtn" data-target="#editModal" data-toggle="modal" >Edit</button>
                    
                                     @csrf
                                     @method('DELETE')
                       
                                     <button type="submit" class="btn btn-danger">Delete</button>
                                 </form>
                             </td>


                             @endforeach
                          </tbody>

              
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- END DATA TABLE -->
</div>

@endsection

resources/views/admin/purchase/managePurchase.blade.php
@extends('layouts.admin')
@section('content')
<div class="container mmt mb-5">
   <!-- DATA TABLE -->
   <div class="card shadow mb-4 datatable-card">
      <div class="card-header py-3">
         <h3 class="mb-4 font-weight-bold  ml-sm-1">Manage Purchase</h3>
         <form action="" method="POST">
            <div class="form-row align-items-center">
               <div class="col-md-3">
                  <label class="mr-sm-2" for="inlineFormCustomSelect">Enter Customer Mobile</label>
                  <input id="email" type="text" class="form-control" name="mobile" placeholder="Enter Mobile No">
               </div>
               <div class="col-md-3">
                  <label class="mr-sm-2" for="inlineFormCustomSelect">From Date</label>
                  <div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
                     <input class="form-control form-control-user date-form" type="text" name="from" placeholder="Enter From Date" required="">
                     <span class="input-group-addon date-form-addon align-items-center d-flex pl-1"><i class="fa fa-calendar"></i></span>
                  </div>
               </div>
               <div class="col-md-3">
                  <label class="mr-sm-2" for="inlineFormCustomSelect">To Date</label>
                  <div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
                     <input class="form-control form-control-user date-form" type="text" name="to" placeholder="Enter To Date" required="">
                     <span class="input-group-addon date-form-addon align-items-center d-flex pl-1"><i class="fa fa-calendar"></i></span>
                  </div>
               </div>
               <div class="col-md-3 mt-lg-auto mb-lg-1 mt-md-auto mb-md-1 mt-sm-4">
                  <button type="submit" class="btn btn1" name="submit">Search</button>
               </div>
            </div>
         </form>
      </div>
      <div class="card-body">
         <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
               <div class="row">
                  <div class="col-sm-12 col-md-6">
                     <div class="dataTables_length" id="dataTable_length">
                        <label>
                           Show 
                           <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                              <option value="10">10</option>
                              <option value="25">25</option>
                              <option value="50">50</option>
                              <option value="100">100</option>
                           </select>
                           entries
                        </label>
                     </div>
                  </div>
                  <div class="col-sm-12 col-md-6">
                     <div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12">
                     <table class="table table-bordered text-center dataTable no-footer" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
                        <thead>
                           <tr role="row">
                              <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 90.5167px;" aria-sort="ascending" aria-label="Date: activate to sort column descending">Date</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 97.6667px;" aria-label="Bill No: activate to sort column ascending">Bill No</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 99.5px;" aria-label="Phone No: activate to sort column ascending">Phone No</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 66.9833px;" aria-label="Name: activate to sort column ascending">Name</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 90.8833px;" aria-label="City: activate to sort column ascending">City</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 105.767px;" aria-label="State: activate to sort column ascending">State</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 88.8167px;" aria-label="Address: activate to sort column ascending">Address</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 44.4833px;" aria-label="Edit: activate to sort column ascending">Edit</th>
                              <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 70.3833px;" aria-label="Delete: activate to sort column ascending">Delete</th>
                           </tr>
                        </thead>
                        <tbody>
                           <!-- SEARCH CUSTOMER TABLE-->
                           <!-- ALL CUSTOMERS TABLE-->
                           <tr role="row" class="odd">
                              <td class="sorting_1">2020-10-09</td>
                              <td>7055572245</td>
                              <td>9536087919</td>
                              <td>test</td>
                              <td>dehradun 1</td>
                              <td>Uttarakhand</td>
                              <td>Dehradun</td>
                              <td><a href="edit-supplier-purchase.php?purchase_id=3"><i class="fa fa-edit font-aw"></i></a></td>
                              <td><a href="delete.php?agree_id=3"><i class="fas fa-trash-alt"></i></a></td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
               </div>
               <div class="row">
                  <div class="col-sm-12 col-md-5">
                     <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 1 of 1 entries</div>
                  </div>
                  <div class="col-sm-12 col-md-7">
                     <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                        <ul class="pagination">
                           <li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
                           <li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                           <li class="paginate_button page-item next disabled" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">Next</a></li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- END DATA TABLE -->
</div>
@endsection

resources/views/admin/purchase/managepayment.blade.php
@extends('layouts.admin')
@section('content')
<div class="section__content section__content--p30 pb-5`">
    <div class="container-fluid">
                <!-- DATA TABLE -->
<div class="card shadow mb-4 datatable-card">
<div class="card-header py-3">
<div class="row">
<div class="col-sm-6">
  <h3 class="mb-4 font-weight-bold text-primary ml-sm-1">Manage Supplier Payment</h3>
</div>
<div class="col-sm-6">
  <button type="button" class="btn btn-primary add-payment"><a href="add-supplier-payment.php" style="color: white;">ADD PAYMENT</a></button>
</div>
</div>
<h5 class="badge-success text-center" id="message"></h5>
<form action="" method="POST">
<div class="form-row align-items-center">
<div class="col-md-3">
<label class="mr-sm-2" for="inlineFormCustomSelect">Enter Customer Mobile</label>
<input id="email" type="text" class="form-control" name="mobile-no" placeholder="Enter Mobile No" required="">
</div>
<div class="col-md-3">
<label class="mr-sm-2" for="inlineFormCustomSelect">From Date</label>
<div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
<input class="form-control form-control-user date-form" type="text" name="from" placeholder="Start Date" required="">
<span class="input-group-addon date-form-addon"><i class="fa fa-calendar"></i></span>
</div> 
</div>
<div class="col-md-3">
<label class="mr-sm-2" for="inlineFormCustomSelect">To Date</label>
<div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
<input class="form-control form-control-user date-form" type="text" name="to" placeholder="Start Date" required="">
<span class="input-group-addon date-form-addon"><i class="fa fa-calendar"></i></span>
</div> 
</div>
<div class="col-md-3 mt-lg-auto mb-lg-1 mt-md-auto mb-md-1 mt-sm-4">
<button type="submit" name="submit" class="btn btn-primary">Search</button>
</div>
</div>
</form>
</div>
<div class="card-body mb-5">
<div class="table-responsive">
<div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer"><div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row"><div class="col-sm-12"><table class="table table-bordered text-center dataTable no-footer" id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" width="100%" cellspacing="0">
  <thead>
    <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 51.8333px;" aria-sort="ascending" aria-label="Date: activate to sort column descending">Date</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 95.6333px;" aria-label="Phone No: activate to sort column ascending">Phone No</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 64px;" aria-label="Name: activate to sort column ascending">Name</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 158.833px;" aria-label="Payment Status: activate to sort column ascending">Payment Status</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 143.617px;" aria-label="Payment Type: activate to sort column ascending">Payment Type</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 174.617px;" aria-label="Payment Amount: activate to sort column ascending">Payment Amount</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 42.1167px;" aria-label="Edit: activate to sort column ascending">Edit</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" style="width: 67.35px;" aria-label="Delete: activate to sort column ascending">Delete</th></tr>
  </thead>
  <tbody>
    <!-- ALL CUSTOMERS TABLE-->
                      <tr class="odd"><td colspan="8" class="dataTables_empty" valign="top">No data available in table</td></tr></tbody>
</table></div></div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 0 to 0 of 0 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item next disabled" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">Next</a></li></ul></div></div></div></div>
</div>
</div>
</div>


                <!-- END DATA TABLE -->
           
  </div>
</div>

@endsection

resources/views/admin/purchase/transaction.blade.php
@extends('layouts.admin')
@section('content')
  <div class="container mmt mb-5">
    <!-- DATA TABLE -->
    <div class="card shadow mb-4 datatable-card">
      <div class="card-header py-3">
        <h3 class="mb-4 font-weight-bold ml-sm-1">Supplier Transactions</h3>
        <form action="" method="POST">
           <div class="form-row align-items-center">
              <div class="col-md-3">
                 <label class="mr-sm-2" for="inlineFormCustomSelect">Enter Customer Mobile</label>
                 <input id="email" type="text" class="form-control" name="mobile" placeholder="Enter Mobile No">
              </div>
              <div class="col-md-3">
                 <label class="mr-sm-2" for="inlineFormCustomSelect">From Date</label>
                 <div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
                    <input class="form-control form-control-user date-form" type="text" name="from" placeholder="Enter From Date" required="">
                    <span class="input-group-addon date-form-addon align-items-center d-flex pl-1"><i class="fa fa-calendar"></i></span>
                 </div>
              </div>
              <div class="col-md-3">
                 <label class="mr-sm-2" for="inlineFormCustomSelect">To Date</label>
                 <div class="input-group date datepicker" data-date-format="dd-mm-yyyy">
                    <input class="form-control form-control-user date-form" type="text" name="to" placeholder="Enter To Date" required="">
                    <span class="input-group-addon date-form-addon align-items-center d-flex pl-1"><i class="fa fa-calendar"></i></span>
                 </div>
              </div>
              <div class="col-md-3 mt-lg-auto mb-lg-1 mt-md-auto mb-md-1 mt-sm-4">
                 <button type="submit" class="btn btn1" name="submit">Search</button>
              </div>
           </div>
        </form>
     </div>
    </div>
  </div>
@endsection